// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBJGvC8BCKLsevPyL4wKSJh8G27dMC_1MY',
    appId: '1:868173664084:android:f5fc1c6e88604d880302c1',
    messagingSenderId: '868173664084',
    projectId: 'youme-cf830',
    storageBucket: 'youme-cf830.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyABY61uWsMyL6vKWocvSu0MjpvCFcZoUrU',
    appId: '1:868173664084:ios:7098f91b09b2df930302c1',
    messagingSenderId: '868173664084',
    projectId: 'youme-cf830',
    storageBucket: 'youme-cf830.appspot.com',
    androidClientId: '868173664084-bprr6agtm7b4tqsqbo7nrjg0b2qm55bj.apps.googleusercontent.com',
    iosClientId: '868173664084-0n1fuirkh93j7muotbf24a7lhtmfhb05.apps.googleusercontent.com',
    iosBundleId: 'com.app.youmechat.youMe',
  );
}
